{{- if eq (include "radosgw-exporter.createSecret" .) "true" }}
{{- include "radosgw-exporter.validateCredentials" . -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "radosgw-exporter.secretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "radosgw-exporter.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.exporter.credentials.accessKey }}
  accessKey: {{ .Values.exporter.credentials.accessKey | b64enc | quote }}
  {{- else }}
  accessKey: ""  # Empty value, to be filled later
  {{- end }}
  {{- if .Values.exporter.credentials.secretKey }}
  secretKey: {{ .Values.exporter.credentials.secretKey | b64enc | quote }}
  {{- else }}
  secretKey: ""  # Empty value, to be filled later
  {{- end }}
{{- end }}